# Generated by Django 4.2 on 2023-05-03 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('transactions', '0002_currency_transaction_remove_points_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='currency',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='register.userprofile'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=3),
        ),
    ]
