# Generated by Django 4.2 on 2023-05-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_delete_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('GBP', 'GBP'), ('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=3),
        ),
    ]
