# Generated by Django 4.2 on 2023-05-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0006_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
    ]
